theme: jekyll-theme-minimal
title: FashionStack 
logo: https://picfiles.alphacoders.com/484/484186.jpg
description: Criando projetos focado na visão sustentável e acessível  .... 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
