theme: jekyll-theme-minimal
title: Fashion Stack Ltda
logo: https://picfiles.alphacoders.com/484/484186.jpg
description: Documentação 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
